### GET

GET 127.0.0.1:8080/billing-codes
Accept: application/json

### POST

POST 127.0.0.1:8080/billing-codes
Content-Type: application/json
Accept: application/json

{
  "type" : 1,
  "hotelIds" : ["111", "112", "113"]
}
