-- MySQL Script generated by MySQL Workbench
-- Thu Nov  4 22:37:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tour
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tour` ;

-- -----------------------------------------------------
-- Schema tour
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tour` DEFAULT CHARACTER SET utf8 ;
USE `tour` ;

-- -----------------------------------------------------
-- Table `tour`.`hotels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour`.`hotels` ;

CREATE TABLE IF NOT EXISTS `tour`.`hotels` (
  `hotel_id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` INT NOT NULL DEFAULT 0,
  `name` VARCHAR(300) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(100) NOT NULL,
  `room_count` INT NOT NULL DEFAULT 0,
  `created_by` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `modified_by` VARCHAR(45) NULL,
  `modified_at` DATETIME NULL,
  PRIMARY KEY (`hotel_id`),
  INDEX `INDEX_NAME_STATUS` (`name` ASC, `status` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tour`.`hotel_rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tour`.`hotel_rooms` ;

CREATE TABLE IF NOT EXISTS `tour`.`hotel_rooms` (
  `hotel_room_id` BIGINT NOT NULL AUTO_INCREMENT,
  `hotels_hotel_id` BIGINT NULL,
  `room_number` VARCHAR(100) NOT NULL,
  `room_type` INT NOT NULL,
  `original_price` DECIMAL(18,2) NOT NULL,
  `created_by` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `modified_by` VARCHAR(45) NULL,
  `modified_at` DATETIME NULL,
  PRIMARY KEY (`hotel_room_id`),
  INDEX `fk_hotel_rooms_hotels_idx` (`hotels_hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_hotel_rooms_hotels`
    FOREIGN KEY (`hotels_hotel_id`)
    REFERENCES `tour`.`hotels` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
